# Generated by Django 5.2.11 on 2026-03-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_esp32', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leituraenergia',
            name='fator_potencia',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leituraenergia',
            name='pico_de_tensao',
            field=models.FloatField(default=0),
        ),
    ]
