# Generated by Django 5.2.11 on 2026-03-09 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_esp32', '0002_leituraenergia_fator_potencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletrodomestico',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('PICO', 'Pico de Tensão'), ('SOBRECONSUMO', 'Sobreconsumo de Energia'), ('ESTABILIZADO', 'Equipamento Estabilizado'), ('NORMAL', 'Tensão Normalizada'), ('MANUTENCAO', 'Manutenção Próxima')], max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracaoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_kwh', models.FloatField(default=100)),
                ('periodo_alarme', models.CharField(choices=[('DIARIO', 'Diário'), ('MENSAL', 'Mensal')], default='MENSAL', max_length=10)),
                ('alarme_ativo', models.BooleanField(default=True)),
                ('eletrodomestico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_esp32.eletrodomestico')),
            ],
        ),
    ]
