# Generated by Django 5.2.12 on 2026-04-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_esp32', '0003_eletrodomestico_is_mock_alter_evento_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletrodomestico',
            name='limite_curto_circuito',
            field=models.FloatField(default=25),
        ),
        migrations.AddField(
            model_name='eletrodomestico',
            name='limite_subcorrente',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='eletrodomestico',
            name='limite_subtensao',
            field=models.FloatField(default=190),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('PICO', 'Pico de Tensão'), ('SUBTENSAO', 'Subtensão'), ('SOBREINTENSIDADE', 'Sobreintensidade'), ('SUBINTENSIDADE', 'Subintensidade'), ('CURTO_CIRCUITO', 'Curto-circuito (fusível)'), ('SOBRECONSUMO', 'Sobreconsumo de Energia'), ('ESTABILIZADO', 'Equipamento Estabilizado'), ('NORMAL', 'Tensão Normalizada'), ('MANUTENCAO', 'Manutenção Próxima')], max_length=20),
        ),
    ]
