# Generated by Django 5.2.12 on 2026-04-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_esp32', '0004_eletrodomestico_limite_curto_circuito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('eletrodomestico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_manutencao', to='app_esp32.eletrodomestico')),
            ],
        ),
    ]
