# Generated by Django 5.2.12 on 2026-04-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_esp32', '0005_manutencaoagendada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eletrodomestico',
            name='data_manutencao',
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('PICO', 'Pico de Tensão'), ('SUBTENSAO', 'Subtensão'), ('SOBREINTENSIDADE', 'Sobreintensidade'), ('SUBINTENSIDADE', 'Subintensidade'), ('CURTO_CIRCUITO', 'Curto-circuito (fusível)'), ('SOBRECONSUMO', 'Sobreconsumo de Energia'), ('ESTABILIZADO', 'Equipamento Estabilizado'), ('NORMAL', 'Tensão Normalizada')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ManutencaoAgendada',
        ),
    ]
