# Generated by Django 5.2.12 on 2026-04-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_esp32', '0006_remove_eletrodomestico_data_manutencao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletrodomestico',
            name='rele_ligado',
            field=models.BooleanField(default=True),
        ),
    ]
