# Generated by Django 5.2.12 on 2026-04-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_esp32', '0007_eletrodomestico_rele_ligado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eletrodomestico',
            name='limite_subcorrente',
        ),
        migrations.RemoveField(
            model_name='eletrodomestico',
            name='limite_subtensao',
        ),
        migrations.AlterField(
            model_name='eletrodomestico',
            name='limite_corrente',
            field=models.FloatField(default=15),
        ),
        migrations.AlterField(
            model_name='eletrodomestico',
            name='limite_tensao',
            field=models.FloatField(default=240),
        ),
    ]
