# Generated by Django 5.2.12 on 2026-04-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_esp32', '0008_remove_eletrodomestico_limite_subcorrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletrodomestico',
            name='limite_subcorrente',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='eletrodomestico',
            name='limite_subtensao',
            field=models.FloatField(default=190),
        ),
        migrations.AlterField(
            model_name='eletrodomestico',
            name='limite_corrente',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='eletrodomestico',
            name='limite_tensao',
            field=models.FloatField(default=250),
        ),
    ]
