# Generated by Django 5.2.12 on 2026-04-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_esp32', '0009_eletrodomestico_limite_subcorrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletrodomestico',
            name='fator_potencia_nominal',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='eletrodomestico',
            name='frequencia_rede',
            field=models.FloatField(default=60.0),
        ),
        migrations.AddField(
            model_name='eletrodomestico',
            name='numero_sensor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eletrodomestico',
            name='limite_corrente',
            field=models.FloatField(default=8.0),
        ),
        migrations.AlterField(
            model_name='eletrodomestico',
            name='limite_potencia',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AlterField(
            model_name='eletrodomestico',
            name='limite_tensao',
            field=models.FloatField(default=230.0),
        ),
    ]
